# This script requires a Personal access token to be created. The token
# should be added as a repository secret called "RELEASE_PLEASE" under
# https://github.com/OWNER/REPO/settings/secrets/actions
#
# NB: Fine grained PATs do NOT work, only classic PATs work at this time
# The permissions required are:
# repo
# write-packages (for writing to the github registry)

name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          always-auth: true

      - name: Install npm packages
        run: yarn --frozen-lockfile

      - name: Build package
        run: yarn build-dev

      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{secrets.REPO_TOKEN}}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Debug Release Outputs
        run: |
          echo ${{ steps.release.outputs.release_created }}
          echo ${{ toJson(steps.release.outputs) }}

      - name: Report ref
        if: ${{ steps.release.outputs.release_created }}
        run: echo ${{ steps.release.outputs.tag_name }}

      # Publish to Github's NPM registry
      - name: Publish to Github NPM registry
        if: ${{ steps.release.outputs.release_created }}
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish documentation
        if: ${{ steps.release.outputs.release_created }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './dist-storybook/sb'
